# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: juanuribe513
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: projects
# "service" is the name of this project. This will also be added to your AWS resource names.
service: daily-inspiration-aws-node

stages:
  default:
    params:
      tableName: "users-table-${sls:stage}"
      region: ${self:provider.region}

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  profile: serverless
  stage: dev
  iam:
    role:
      statements:
        - Effect: Allow
          Action: s3:*
          Resource: "*"
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]
  environment:
    USERS_TABLE: ${param:tableName}
    REGION: ${param:region}

functions:
  quotes:
    handler: handler/getQuotes.getQuotes
    events:
      - http:
          path: quotes
          method: get
          cors: true

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:tableName}
