# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: juanuribe513
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: projects
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-node-todos

stages:
  default:
    params:
      tableName: "users-table-${sls:stage}"

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]
  environment:
    TODOS_TABLE: ${param:tableName}

functions:
  create:
    handler: handler/createTodo.createTodo
    events:
      - http:
          path: todos/create
          method: post
          cors: true

  list:
    handler: handler/listTodos.listTodos
    events:
      - http:
          path: todos/list
          method: get
          cors: true

  get:
    handler: handler/getTodo.getTodo
    events:
      - http:
          path: todos/{id}
          method: get
          cors: true

  delete:
    handler: handler/deleteTodo.deleteTodo
    events:
      - http:
          path: todos/delete/{id}
          method: delete
          cors: true

  update:
    handler: handler/updateTodo.updateTodo
    events:
      - http:
          path: todos/update/{id}
          method: put
          cors: true

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:tableName}
