service: final-aws-ses-email

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "ses:*"
          Resource:
            - "*"

functions:
  create:
    handler: handler.createContact
    events:
      - http:
          path: /contact-us
          method: post
          cors: true

package:
  patterns:
    - '!node_modules/**'
    - '!tests/**'
    - '!.git/**'
    - '!README.md'